### ISSUE TITLE
Неправильная кодировка файла tokens

### ISSUE THREAD

**Issue by matrohin** [fiddenmar/pybico_crf#22]
При запуске python learn.py выдаёт следующую ошибку.

Traceback (most recent call last):
  File "learn.py", line 18, in <module>
    token_lines = file_with_tokens.readlines()
  File "D:\Programs\python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 29: character maps to <undefined>

Workaround: Изменить кодировку tokens на 1251.
Скорее всего вам необходимо прописать вручную с помощью какой кодировки открывать файл.

**Comment by fiddenmar** [comment]
У нас используется кодировка UTF-8. Windows-кодировки не поддерживаются, как и сама операционная система Windows.

**Comment by IvanElenskiy** [comment]
> У нас используется кодировка UTF-8. Windows-кодировки не поддерживаются, как и сама операционная система Windows.

Это странное заявление, ведь заказчик (кафедра, если не ошибаюсь) на 90% точно - WindowsOnly-машины без виртуалок. Стоит уточнить необходимость такого ограничения.
Завел хотелку на кодировки #25

**Comment by fiddenmar** [comment]
Заказчик - обладатель ноутбука с Debian Jessie, в настоящее время поддержка включает только Linux-like, о чем написано в техническом задании на проект.

Расширение поддержки на Windows не планируется.

**Comment by matrohin** [comment]
Эта проблема решается открытием файла в другой кодировке. Вы не против, чтобы я исправил эту проблему?
Всё будет работать и в линуксе с другой кодировкой (там можно изменить стандартную кодировку, так что у вас могут быть проблемы, если там не utf-8), и в windows.
Только разрешите доступ, я создам ветку и pull request.

EDIT: На самом деле может я и неправ с тем, что нужно тогда переделать всё под utf-8.
Может пользователь всё таки будет создавать свой tokens в своей кодировке. Не знаю. Может тогда стоит это указать в readme.
