### ISSUE TITLE
Использование deprecated модулей

### ISSUE THREAD

**Issue by matrohin** [fiddenmar/pybico_crf#23]
При вызове python learn.py каждый раз выводится сообщение:
D:\Programs\python\lib\site-packages\sklearn\cross_validation.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored class
es and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
D:\Programs\python\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes an
d functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

Так как, это будет затруднять будущую разработку (deprecated модули будут удалены), то лучше избавиться от их использования сейчас

**Comment by fiddenmar** [comment]
Мы не используем эти функции напрямую, это зависимость одного из внешних модулей (sklearn-crfsuite).
