### ISSUE TITLE
Неправильное сообщение usage в pybico_crf

### ISSUE THREAD

**Issue by matrohin** [fiddenmar/pybico_crf#24]
При команде: python pybico_crf.py -a
выводит:
usage: python3 pybico_crf.py [-s <inputString>]

На самом деле этот файл поддерживает другие/больше командных аргументов, чем написано в usage.

**Comment by fiddenmar** [comment]
Дублирование задач, в настоящее время уже имеется задача #20, нужно было оставить комментарий там.

**Comment by fiddenmar** [comment]
Актуально после закрытия #20, в котором будут проведены изменения в документации.
