### ISSUE TITLE
Внедрить поддержку наиболее популярных текстовых кодировок

### ISSUE THREAD

**Issue by IvanElenskiy** [fiddenmar/pybico_crf#25]
Можно написать/использовать существующий алгоритм распознавания кодировки, чтобы пользователь не занимался лишней работой (и не ошибался) по выбору из списка.
Ожидается, что список поддерживаемых кодировок будет содержать бОльшую часть кириллических для удобства пользователя.

**Comment by fiddenmar** [comment]
#22
